services:
  go_app:
    build: .
    container_name: go_app
    environment:
      - AUTH_TOKEN=${AUTH_TOKEN}
    restart: always
    healthcheck:
      test: "wget -qO- http://localhost:8080/health || exit 1"
    ports:
      - "8080"

  # cloudflared:
  #   image: cloudflare/cloudflared:latest
  #   command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}
  #   container_name: cloudflared
  #   environment:
  #     - TUNNEL_TOKEN=${TUNNEL_TOKEN}
  #   restart: always
