services:
  go_app:
    build: .
    container_name: go_app
    environment:
      - API_KEY=${API_KEY}
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - data:/app/data

  # cloudflared:
  #   image: cloudflare/cloudflared:latest
  #   command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}
  #   container_name: cloudflared
  #   environment:
  #     - TUNNEL_TOKEN=${TUNNEL_TOKEN}
  #   restart: always

volumes:
  data:
